#!/usr/bin/env python

import os
import signal
import sys
import subprocess

from pathlib import Path
from subprocess import call as _call


PATH_HERE = Path(__file__).parent
PATH_REPO = PATH_HERE.parent
PATH_CHECKOUT = PATH_REPO.parent / PATH_REPO.name.removesuffix('.git')
PATH_PID = PATH_CHECKOUT / '__pid__'


def call(command):
    command = command.split() if type(command) == str else command
    print(f"Calling {' '.join(command)}")
    return _call(command)


def git(command):
    call(f"git --git-dir={PATH_REPO} --work-tree={PATH_CHECKOUT} {command}")


def main(branch):

    if not PATH_CHECKOUT.is_dir():
        PATH_CHECKOUT.mkdir()

    print(f"On branch: {branch} @ {PATH_REPO}")

    git(f"checkout {branch}")

    os.chdir(PATH_CHECKOUT)

    call('python -m venv venv')

    PY = Path('venv', 'Scripts', 'python.exe')
    call(f'{PY} -m pip install .')

    proc = subprocess.Popen(
        [PY.parent / 'bbuild.exe' ],
        creationflags=subprocess.DETACHED_PROCESS
    )

    if PATH_PID.is_file():
        os.kill(int(PATH_PID.read_text()), signal.SIGTERM)

    PATH_PID.write_text(f"{proc.pid}")
    print(f"Written pid: {proc.pid} to {PATH_PID}")


if __name__ == "__main__":
    _, _, ref = sys.stdin.readlines()[0].split()
    main(ref.removeprefix('refs/heads/'))
