#!/usr/bin/env python

import sys

from pathlib import Path
from subprocess import call as _call


PATH_REPO = Path(__file__).parent.parent
PATH_CHECKOUT = PATH_REPO.parent / PATH_REPO.name.removesuffix('.git')


def call(command):
    command = command.split() if type(command) == str else command
    print(f"Calling {command}")
    return _call(command)


def main(branch):
    print(f"on branch: {branch} @ {PATH_REPO}")


if __name__ == "__main__":
    _, _, ref = sys.stdin.readlines()[0].split()
    main(ref.removeprefix('refs/heads/'))
